# Generated by Django 4.2.9 on 2024-01-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cooking_time', models.PositiveIntegerField()),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
